### ISSUE TITLE
Images are not showing (WEB)

### ISSUE THREAD

**Issue by SjoenH** [equinor/mad-project-ergonomics-web#62]
Images are not working atm. First, the issue was Omnia added a subscription key... but we decided to move away from Omnia, so we got new API endpoints where the images don't need a header to fetch, so not an issue anymore, but we need to point the web-app to the new endpoints.

Fix it by changing endpoints to:
`https://api.statoil.com/app/ergonomics/dev`

ref: Same issue for the App https://github.com/equinor/mad-project-ergonomics-client/issues/93

## Requirements
Get pictures to work on all environments

**Comment by SjoenH** [comment]
@dbjoEq do you know why this card is in the "ice" column?
Moving it to "waiting for developer" and assigning @PtjeEquinor as well.

**Comment by PtjeEquinor** [comment]
@ntorsen Ready for testing in Dev, Test and Qa. Links here https://github.com/equinor/mad-project-ergonomics-web

**Comment by PtjeEquinor** [comment]
This fix involve changing environment config so it should be tested in prod after deployment, this could be done by the person deploying?

**Comment by ntorsen** [comment]
@PtjeEquinor Images are showing in Dev, Test and QA for Web💪

**Comment by SegarJJ** [comment]
@ntorsen was this one finished up?  I dont recall...

**Comment by dansvend** [comment]
I think @PtjeEquinor should be the one following up on this since he's the one who's been working on this task 💪

**Comment by dansvend** [comment]
In the description it says it needs to be fixed for both web and iOS. Has this been fixed for iOS as well @PtjeEquinor ? If not it would be a good idea to create a new issue in the iOS repo and get it fixed 👌

**Comment by PtjeEquinor** [comment]
The urls are fixed in @dbjoEq´s Expo branch for IOS. I get images in the app from test-flight so looks like it already done in IOS

**Comment by PtjeEquinor** [comment]
Its not deployed, but is ready as far as i know. What is the process of deploying @ntorsen?

**Comment by ntorsen** [comment]
@PtjeEquinor Since we have already deployed Ergonomics version 1.0.1 in Hub for iOS, and informed users that it is available- I think that in this case we can just deploy it to production for web (no need for a release planning meeting). Regarding the process of deploying- I think it is to press the button "Prod" in Azure DevOps, but @dansvend is probably the best one to answer that question

**Comment by dansvend** [comment]
This is now released to [production](https://ergonomics-web-prod.azurewebsites.net/) 🚀 Can you verify that this is working as intended @ntorsen ? 💪

**Comment by ntorsen** [comment]
Working as intended in prod @dansvend 👌

**Comment by dansvend** [comment]
Nice! Thanks for testing @ntorsen 🧪 💯
